### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by zachary822**
Seems to pass all tests.
[base32-0.2.2.0-tasty.log](https://github.com/emilypi/Base32/files/11644425/base32-0.2.2.0-tasty.log)

### CODE REVIEW

**Review by emilypi — APPROVED** [review]

**Comment by emilypi** [comment]
If it passes CI i'll merge and release a revision - thanks 👍

**Comment by emilypi** [comment]
I'm actually going to update this in #20 with a more complete set of maintenance responsibilities I need to perform.

**Comment by emilypi** [comment]
@mitchellwrosen  and @zachary822 would you guys be disproportionately affected by my bumping `bytestring` and `text` to the latest significant major version (`bytestring ^>=0.11` and `text ^>= 2.0` resp.)?

**Comment by zachary822** [comment]
You can close this PR as needed. Thank you for the updates!

**Comment by emilypi** [comment]
Cheers, thanks for the push

**Comment by emilypi** [comment]
It's now up on Hackage as https://hackage.haskell.org/package/base32-0.3 - feel free to bump

**Pull request closed without merging**
